### ISSUE TITLE
ENH: improve readme with formatting (linked to  #15)

### ISSUE THREAD

**Issue by mathurinm** [QB3/CLaR#10]
add:
- [x] reference to Neurips paper
- [x] add bibtex snippet
- [x] link to sphinx documentation
- [x] format citation in paragraphs

**Comment by QB3** [comment]
What do you mean by "add bibtex snippet" @mathurinm ?
Could you point me to smth similar on https://raw.githubusercontent.com/mathurinm/celer/master/README.rst ?

**Comment by mathurinm** [comment]
@QB3 yes:
Cite
====

If you use this code, please cite:

::

    @InProceedings{pmlr-v80-massias18a,
      title = 	 {Celer: a Fast Solver for the Lasso with Dual Extrapolation},
      author = 	 {Massias, Mathurin and Gramfort, Alexandre and Salmon, Joseph},
      booktitle = 	 {Proceedings of the 35th International Conference on Machine Learning},
      pages = 	 {3321--3330},
      year = 	 {2018},
      volume = 	 {80},
    }

::

    @article{massias2019dual,
    title={Dual Extrapolation for Sparse Generalized Linear Models},
    author={Massias, Mathurin and Vaiter, Samuel and Gramfort, Alexandre and Salmon, Joseph},
    journal={arXiv preprint arXiv:1907.05830},
    year={2019}
    }

**Comment by QB3** [comment]
OK great perfect
